### ISSUE TITLE
Problem with aGauge when Reagion Format is Persian

### ISSUE THREAD

**Issue by dara1400** [Code-Artist/AGauge#8]
Hello

Thanks for your great package.
It is working well but when I change my Region Format in control panel to Persian, I counter this error:

System.InvalidOperationException
  HResult=0x80131509
  Message=Failed to initialize because CategoryName is missing.
  Source=System
  StackTrace:
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.EndInit()
   at WindowsFormsApp1.Form1.InitializeComponent() in C:\Users\user\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.Designer.cs:line 141
   at WindowsFormsApp1.Form1..ctor() in C:\Users\user\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 17
   at WindowsFormsApp1.Program.Main() in C:\Users\user\source\repos\WindowsFormsApp1\WindowsFormsApp1\Program.cs:line 18

![image](https://user-images.githubusercontent.com/31727520/110781580-54c95100-827b-11eb-8e5a-11b993448d1b.png)

Would you take a lock at it?

Best Regards

**Comment by Code-Artist** [comment]
Dear sir,

Unfortunately,  I couldn't simulate the same error on my end.
Are you able to debug the project from Visual Studio? That could tell you what is the actual problem.
By the way, the attached image are 2 different issue?

We could try to help if you could share more info.

**Comment by dara1400** [comment]
Hello
result of this code for bounding box is (0,0) when region is Arabic or Persian

SizeF boundingBox = gMeasure.MeasureString("0123456789", Font, -1, StringFormat.GenericTypographic);

**Comment by Code-Artist** [comment]
Hello,

I don't know Arabic or Persian language.
Maybe this article will help.
https://stackoverflow.com/questions/32067032/why-graphics-measurestring-measures-arabic-strring-incorrectly
